=== paulmordont/EPAM-Mentoring/Mentoring.Xml/BooksSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="BooksSchema"
    elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:simpleType name="Genre">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Science fiction"/>
      <xs:enumeration value="History"/>
      <xs:enumeration value="Science"/>
      <xs:enumeration value="Comics"/>
      <xs:enumeration value="Biographies"/>
      <xs:enumeration value="Fantasy"/>
      <xs:enumeration value="Children's"/>
      <xs:enumeration value="Drama"/>
      <xs:enumeration value="Romance"/>
      <xs:enumeration value="Action and Adventure"/>
      <xs:enumeration value="Satire"/>
      <xs:enumeration value="Poetry"/>
      <xs:enumeration value="Horror"/>
      <xs:enumeration value="Novel"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ISBN">
    <xs:restriction base="xs:string">
      <xs:pattern value="((978[\--– ])?[0-9][0-9\--– ]{10}[\--– ][0-9xX])|((978)?[0-9]{9}[0-9Xx])"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="Book">
    <xs:sequence>
      <xs:element name="id" type="xs:string"/>
      <xs:element name="isbn" type="ISBN" minOccurs="0"/>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="author"/>
      <xs:element name="genre" type="Genre" />
      <xs:element type="xs:date" name="publish_date" />
      <xs:element type="xs:date" name="registration_date"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Books">
    <xs:sequence>
      <xs:element name="book" type="Book" minOccurs="0" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="books" type="Books">
    <xs:unique name="uniqueId">
      <xs:selector xpath="book"></xs:selector>
      <xs:field xpath="id"></xs:field>
    </xs:unique>
  </xs:element>
  
</xs:schema>

=== paulmordont/EPAM-Mentoring/Mentoring.Xml/Books.xml
<?xml version="1.0" encoding="utf-8" ?>
<books xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation=".\BooksSchema.xsd">
  <book>
    <id>1</id>
    <isbn>9781451678192</isbn>
    <name>The Martian Chronicles</name>
    <author>Ray Bradbury</author>
    <genre>Science fiction</genre>
    <publish_date>2012-04-17</publish_date>
    <registration_date>2012-04-17</registration_date>
  </book>
  <book>
    <id>2</id>
    <isbn>9780060512804</isbn>
    <name>Cryptonomicon</name>
    <author>Neal Stephenson</author>
    <genre>Novel</genre>
    <publish_date>2002-11-05</publish_date>
    <registration_date>2002-11-05</registration_date>
  </book>
  <book>
    <id>3</id>
    <isbn>9780441569595</isbn>
    <name>Neuromancer</name>
    <author>William Gibson</author>
    <genre>Science fiction</genre>
    <publish_date>1984-07-01</publish_date>
    <registration_date>1984-07-01</registration_date>
  </book>
  <book>
    <id>4</id>
    <isbn>9780748605767</isbn>
    <name>The Pirate </name>
    <author>Sir Walter Scott</author>
    <genre>History</genre>
    <publish_date>2001-04-15</publish_date>
    <registration_date>2001-04-15</registration_date>
  </book>
</books>
